### ISSUE TITLE
Refactoring Monitor type

### ISSUE THREAD

**Issue by haya14busa** [mackerelio/mackerel-client-go#30]
### Problem
Currently, `type Monitor` represents all monitor types, so required fields for each monitor type are unclear.
Also, JSON tag must have `omitempty` because of above reason.

### Solution
Define each monitor type and Monitor interface.

```go
type Monitor interface {
	MonitorType() string // MonitorType() must return monitor type (e.g. connectivity, host, etc...).
}
const (
	monitorTypeConnectivity  = "connectivity"
        // ...
)

// MonitorConnectivity represents connectivity monitor.
type MonitorConnectivity struct {
	ID                   string `json:"id,omitempty"`
	Name                 string `json:"name,omitempty"`
	Type                 string `json:"type,omitempty"`
	IsMute               bool   `json:"isMute,omitempty"`
	NotificationInterval uint64 `json:"notificationInterval,omitempty"`

	Scopes        []string `json:"scopes,omitempty"`
	ExcludeScopes []string `json:"excludeScopes,omitempty"`
}

func (m *MonitorConnectivity) MonitorType() string {
	return monitorTypeConnectivity
}
// ...

func (c *Client) FindMonitors() ([]Monitor, error) {
  // ...
}
func (c *Client) CreateMonitor(param Monitor) (Monitor, error) {
  // ...
}
func (c *Client) DeleteMonitor(monitorID string) (Monitor, error) {
  // ...
}
```

Users can use type switch to access each monitor type like below.

```go
var monitor Monitor = &MonitorConnectivity{}
switch m := monitor.(type) {
  case *MonitorConnectivity:
    fmt.Println(m.Name)
      // ...
}
```

We also needs to handle decoding JSON to each monitors types.
I'm considering to handle this problem by executing unmrashaling twice (1. looking for "type" field and 2. decoding to the monitor type) or decoding to `map[string]interface{}` once and converting it to each monitor type with "type" value using [mitchellh/mapstructure](https://github.com/mitchellh/mapstructure).

### Pull-Request plan
- [x] Introduce monitor interface as unexported name and each monitor type structs.
- [x] Handle JSON decoding and change interface to use new Monitor interface (breaking changes)

Possible additional actions after above works:

- Remove inappropriate `omitempty` tag in each monitor types
- Add additional method of Mointor interface (e.g. add `.GetID()` which returns monitor id). Common keys of monitor JSON are id, name, type, isMute, and notificationInterval.
  - but i think we don't need to add every methods to return value of common key. Thease values often are not enough and users can get each type by type switch.

**Comment by haya14busa** [comment]
## monitors JSON decoding
I implemented two decoding method and run benchmark.

1. method 1: executing unmrashaling twice (1. looking for "type" field and 2. decoding to the monitor type)
2. method 2: decoding to map[string]interface{} once and converting it to each monitor type with "type" value using mitchellh/mapstructure.

patch: https://gist.github.com/haya14busa/e983e3aac3c8932b5f5ffd674ee9038a#file-diff-patch

```
$ go test -v -count=10 -run="^$" -bench=Monitor_JSON_ | benchstat
name                         time/op
Monitor_JSON_mapstructure-4   159µs ± 1%
Monitor_JSON_rawmessage-4    95.2µs ± 6%

Benchmark for larger JSON

$ wc -c monitors.json
24802
$ # change test JSON to monitors.json
$ go test -v -run="^$" -bench=Monitor_JSON_ | prettybench
benchmark                              iter    time/iter
---------                              ----    ---------
BenchmarkMonitor_JSON_mapstructure-4   1000   1.98 ms/op
BenchmarkMonitor_JSON_rawmessage-4     1000   1.40 ms/op
```

I suspected that method 1. might be slow because it needs additional unmarshaling JSON, but bench shows it's faster than method 2 (though both implementations are fast enough, i guess).
method 2 also has downside which requires external package dependencies other than go standard lib.

So, I'll implement method 1 to handle decoding JSON.

**Comment by haya14busa** [comment]
All main refactoring tasks are done! :tada:

As a follow up, we can remove needless `omitempty` tag for each monitor types.

But, I think this issue is closable. Removing `omitempty` tag is not an urgent task.
I (or you) can remove them one by one when we have a time.

**Comment by itchyny** [comment]
Thank you for your great contribution! 👍
